pythonised the three resize tests
highperformancecoder/minsky pull request #527
Opened 2024-11-06 13:39 UTC by wdednam

Once I got the godleyResize.sh test working, it was very easy to pythonise the other resize tests.

2024-11-06 23:21 UTC, highperformancecoder requested changes
Looks good. Just some relatively minor comments for improving these.

2024-11-06 23:21 UTC, highperformancecoder commented on test/00/godleyResize.sh
> +def assert_condition(condition, message="Assertion failed!"):
No need to define this. The inbuilt assert() function of python3 already does this.

2024-11-06 23:21 UTC, highperformancecoder commented on test/00/godleyResize.sh
> +        # Access groups by index, as minsky.model.groups is not directly iterable
Should add this to my todo list. It would be nice if C++ containers were properly iterable in python, rather than just indexable as now.

2024-11-06 23:21 UTC, highperformancecoder commented on test/00/godleyResize.sh
> +godley_icon = findObject("GodleyIcon")
I know this is recapitulating the TCL code, but `minsky.canvas.addGodley()` adds the item to `minsky.canvas.itemFocus()`, so there's no need to do findObject here.

I believe `godley_icon=minsky.canvas.itemFocus()` will simply create the reference you need.

There's two different implementations of the python bindings, the older version here in Minsky, and a newer one being developed in EcoLab, and coming to Minsky soon. So the behaviopur may no correspond with what I remember, and needs to be tested.

2024-11-06 23:21 UTC, highperformancecoder commented on test/00/godleyResize.sh
> +found_godley_icon = findObject("GodleyIcon")
Was this necessary?

2024-11-06 23:21 UTC, highperformancecoder commented on test/00/godleyResize.sh
> +minsky.canvas.redraw()
Also wondering why this is necessary

2024-11-06 23:21 UTC, highperformancecoder commented on test/00/groupResize.sh
> +def findObject(type_name):
This method should be split into a module, as it is generically useful

2024-11-08 12:20 UTC, wdednam reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/527)* status: all files reviewed, 6 unresolved discussions (waiting on @wdednam)



<!-- Sent from Reviewable.io -->

2024-11-09 08:54 UTC, highperformancecoder commented on RESTService/pyminsky.cc
> +  static PyObject* findObject(PyObject* self, PyObject* args)
Interesting. Not what I had in mind, but OK - it does the job.

2024-11-09 08:54 UTC, highperformancecoder approved these changes

2024-11-09 08:57 UTC, highperformancecoder reviewed
<!-- Sent from Reviewable.io -->

2024-11-09 08:57 UTC, highperformancecoder commented on test/00/groupResize.sh
> +def findObject(type_name):
LGTM
<!-- Reviewable comment -OBF81c-1jXmM-XZsvm0:bb6ywmx -->
<!-- Sent from Reviewable.io -->

2024-11-09 08:58 UTC, highperformancecoder approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/highperformancecoder/minsky/527#-:-OBF8R8Y6IVKT1_A6vx7:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @wdednam)



<!-- Sent from Reviewable.io -->

2024-11-09 08:59 UTC, merged